const menu = "menu/";

export const LIGHTS_PANEL_ACTIVATED = menu + "LIGHTS_PANEL_ACTIVATED";
export const NETWORK_PANEL_ACTIVATED = menu + "NETWORK_PANEL_ACTIVATED";
export const SENSORS_PANEL_ACTIVATED = menu + "SENSORS_PANEL_ACTIVATED";
export const SETTINGS_PANEL_ACTIVATED = menu + "SETTINGS_PANEL_ACTIVATED";
export const ACTIVE_PANEL_INDEX_CHANGED = menu + "ACTIVE_PANEL_INDEX_CHANGED";
export const TRANSITION_FINISHED = menu + "TRANSITION_FINISHED";
